### PR TITLE
Remove namespace to work correctly with examples

### PR DESCRIPTION
**Pull request by praveenperera**

### CODE REVIEW

**Comment by FabienHenon** [comment]
What examples are you talking about?

**Comment by praveenperera** [comment]
The one in the readme it should be:

```reason
type person = {
  age: int,
  name: string
};

module Decode = {
  let personDecoder = json =>
    Json.Decode.{
      age: json |> field("age", int),
      name: json |> field("name", string)
    };
};

/* At app launch say you set your data state to `NotAsked` */
let data: BsRemotedata.WebData.t(person) = BsRemotedata.RemoteData.NotAsked;

/* You received an event and you need to retrieve your data */
let data: BsRemotedata.WebData.t(person) = BsRemotedata.RemoteData.Loading;

Fetch.fetch("http://my-api")
|> BsRemotedata.WebData.fromResponse(Decode.personDecoder)
|> Js.Promise.then_(data => {
  /* Here your data is still a WebData.t(person) and will be
    either Success(person), or Failure(httpError) */
});
```

Or you could `open BsRemotedata` in any place where you want to use `RemoteData` if you want to use namespaces. I think this package would be easier to use without the namespace, and I don't think its necessary in this case.

**Comment by FabienHenon** [comment]
Ah, yes you're right.

Maybe you should change your PR to update the README file instead of the namespace? This way, we won't create a breaking change ;)

**Comment by praveenperera** [comment]
I will create a new PR for that.

But I think we should talk about maybe releasing a V2 with this breaking change. I think for this package that would be the way to go. Thoughts?

**Comment by FabienHenon** [comment]
I don't know. What are the general thoughts about this?

**Comment by phillipj** [comment]
I'd love to either see this PR merged or the README updated. As the rookie reason-er I am, I just spent quite a lot of time banging my head against the wall, struggling to understand why I couldn't simply use `WebData` as the examples shows.

Unfortunately I don't know the most idiomatic way of the two approaches suggested here.

**EDIT:** I just discovered that the examples on redex vs GitHub are different for some reason. The redex example currently does *not* include `open BsRemotedata`, whilst it does in the README shown on GitHub. Needless to say, it would have been nice of those were in sync, I assume I would have spent less time chasing this if they were.

**Pull request merged**
